### ISSUE TITLE
Is bibliogram_ynh ready for YH Debian 11?

### ISSUE THREAD

**Issue by rocky-III** [YunoHost-Apps/bibliogram_ynh#39]
Is bibliogram_ynh ready for YH Debian 11?

After an new installation i get this error: 

`Error: No profile info in the preloader.
    at /var/www/bibliogram/src/lib/collectors.js:74:12
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getUserAndQuota (/var/www/bibliogram/src/site/api/routes.js:21:28)
    at async Object.code (/var/www/bibliogram/src/site/api/routes.js:114:29)`

**Comment by MonsieurPoutounours** [comment]
Hi,

Seems it is not. 
Fresh install on Yunohost 11.0.9.3, same error.

**Comment by ericgaspar** [comment]
Please provide full logs and detailed server spec.

**Comment by rocky-III** [comment]
installatin does work but if a search is done you get the error 

```
···<  |        500. That's an error.        |  >···
           ◺―――――――――――――――――――――――――――――――――――――◿


 ╱  Are you visiting this website? Not sure what's going on?  ╲
 ╲             You might want to come back later.             ╱



Error: No profile info in the preloader.
    at /var/www/bibliogram/src/lib/collectors.js:74:12
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getUserAndQuota (/var/www/bibliogram/src/site/api/routes.js:21:28)
    at async Object.code (/var/www/bibliogram/src/site/api/routes.js:114:29)
```

**Comment by ericgaspar** [comment]
Many [public instances](https://git.sr.ht/~cadence/bibliogram-docs/tree/master/docs/Instances.md) seem to have the same issue... My guess is that this is an upstream issue.

**Comment by rocky-III** [comment]
so it not error 503  like here: https://insta.trom.tf/u/zoo

Bur error 500 like here  : https://bib.actionsack.com/
